name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_target: [unit-test, build-test, e2e-test, intg-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install uv
        run: brew install uv

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Create .env file for CI
        run: cp .env.example .env

      - name: Run tests
        env:
          SUDO: ${{ secrets.SUDO || 'true' }}
        run: make ${{ matrix.test_target }}
